# -*- coding: utf-8 -*-
"""q2_1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SzlEx0rR2z7tTMR_hfyWL7MsPg8ntNmq
"""

#from google.colab import files
#uploaded = files.upload()
#!pip install python-bitcoinlib

import bitcoin.wallet
from bitcoin.core import COIN, b2lx, serialize, x, lx, b2x
from utils import *
from bitcoin.core.script import CScript, OP_DUP, OP_HASH160, OP_EQUALVERIFY, OP_CHECKSIG, SignatureHash, SIGHASH_ALL, OP_TRUE, OP_RETURN

bitcoin.SelectParams("testnet") 
my_private_key = bitcoin.wallet.CBitcoinSecret("927wr1sF6cctY8phdKiCochQ7tPTPy5eB8zEBTPsx47iM8N9reY") # Private key in WIF format
my_public_key = my_private_key.pub
my_address = bitcoin.wallet.P2PKHBitcoinAddress.from_pubkey(my_public_key)
print(my_address)

def P2PKH_scriptPubKey(address):
    return [OP_DUP, OP_HASH160, address, OP_EQUALVERIFY, OP_CHECKSIG]

def public_P2PKH_scriptPubKey():
    return [OP_CHECKSIG]

def P2PKH_scriptSig(txin, txout, txin_scriptPubKey):
    signature = create_OP_CHECKSIG_signature(txin, txout, txin_scriptPubKey, my_private_key)
    return[signature, my_public_key]

def send_from_P2PKH_transaction(amount_to_send, txid_to_spend, utxo_index,
                                txout_scriptPubKey):
    txout = create_txout(amount_to_send, txout_scriptPubKey)

    txin_scriptPubKey = public_P2PKH_scriptPubKey()
    txin = create_txin(txid_to_spend, utxo_index)
    txin_scriptSig = P2PKH_scriptSig(txin, txout, txin_scriptPubKey)

    new_tx = create_signed_transaction(txin, txout, txin_scriptPubKey,
                                       txin_scriptSig)

    return broadcast_transaction(new_tx)

if __name__ == '__main__':
    ######################################################################
    amount_to_send = 0.0001
    txid_to_spend = ('feb39306c2f4e2b9db8f9aa7e0c24167f4932359a2ac50b08e7a0a39c2c88d95') 
    utxo_index = 0 
    ######################################################################

    print(my_address) 
    print(my_public_key.hex()) 
    print(my_private_key.hex()) 
    txout_scriptPubKey = P2PKH_scriptPubKey(my_address)
    response = send_from_P2PKH_transaction(amount_to_send, txid_to_spend, utxo_index, txout_scriptPubKey)
    print(response.status_code, response.reason)
    print(response.text)