# -*- coding: utf-8 -*-
"""q2_2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-nVgyRsM7_vlsidEMQs7XO6k1mMgpGgK
"""

#from google.colab import files
#uploaded = files.upload()

#!pip install python-bitcoinlib

import bitcoin.wallet
from bitcoin.core import COIN, b2lx, serialize, x, lx, b2x
from utils import *
from q2_2_1 import first_private_key, second_private_key, first_public_key, second_public_key, third_public_key
from bitcoin.core.script import CScript, OP_DUP, OP_HASH160, OP_EQUALVERIFY, OP_CHECKSIG, SignatureHash, SIGHASH_ALL,OP_TRUE, OP_0, OP_2, OP_3, OP_CHECKMULTISIG

bitcoin.SelectParams("testnet")
my_private_key = bitcoin.wallet.CBitcoinSecret("92i3QHTdRhrUN8qhQ3vSuYqT55JrYvZuTUPwzYKMikAeVgGbXTZ")
my_public_key = my_private_key.pub
my_address = bitcoin.wallet.P2PKHBitcoinAddress.from_pubkey(my_public_key)
print("mine", my_address)

def P2PKH_scriptPubKey(address):
    return [OP_DUP, OP_HASH160, address, OP_EQUALVERIFY, OP_CHECKSIG]

def multi_P2PKH_scriptPubkey():
    return [OP_2, first_public_key, second_public_key, third_public_key, OP_3, OP_CHECKMULTISIG]

def multi_P2PKH_scriptSig(txin, txout, txin_scriptPubKey):
    first_signature = create_OP_CHECKSIG_signature(txin, txout, txin_scriptPubKey, first_private_key)
    second_signature = create_OP_CHECKSIG_signature(txin, txout, txin_scriptPubKey, second_private_key)
    return[OP_0, first_signature, second_signature]

def send_from_P2PKH_transaction(amount_to_send, txid_to_spend, utxo_index,
                                txout_scriptPubKey):
    txout = create_txout(amount_to_send, txout_scriptPubKey)

    txin_scriptPubKey = multi_P2PKH_scriptPubkey()
    txin = create_txin(txid_to_spend, utxo_index)
    txin_scriptSig = multi_P2PKH_scriptSig(txin, txout, txin_scriptPubKey)

    new_tx = create_signed_transaction(txin, txout, txin_scriptPubKey,
                                       txin_scriptSig)

    return broadcast_transaction(new_tx)

if __name__ == '__main__':
    ######################################################################
    amount_to_send = 0.0002
    txid_to_spend = ('79a5c8a8a769855ee0073f0f6e75f0533b5aa77c2614ff40c94b41d64628c32b') 
    utxo_index = 0
    ######################################################################

    print(my_address)
    print(my_public_key.hex()) 
    print(my_private_key.hex()) 
    txout_scriptPubKey = P2PKH_scriptPubKey(my_address)
    response = send_from_P2PKH_transaction(amount_to_send, txid_to_spend, utxo_index, txout_scriptPubKey)
    print(response.status_code, response.reason)
    print(response.text)